name: Tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    env:
      SKIP: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from version.yml
        id: read_version
        run: |
          version=$(yq '.version' version.yml)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag already exists"
            echo "SKIP=true" >> $GITHUB_ENV
          else
            echo "SKIP=false" >> $GITHUB_ENV
          fi
      - name: Create tag
        if: env.SKIP == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v$VERSION
          git push origin v$VERSION